spring:
  application:
    name: BloomWay

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPEN_ROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemini-3-flash-preview
          temperature: 0.0

jwt:
  secret-key: ${JWT_SECRET_KEY}


client:
  url: http:localhost:8080

server:
  port: 2030

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  project-bucket: projects